task/urls.py
from django.urls import path

from task.views import (
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView, TaskDeleteView, TaskSetDoneView
)


urlpatterns = [
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "<int:pk>/set-done/", TaskSetDoneView.as_view(), name="task-set-done"
    ),
]

app_name = "task"

todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("is_done", "-creation_date")

    def __str__(self):
        return f"{self.content} | {self.creation_date}"

task/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError

from task.models import Task, Tag


class TaskCreationForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    expected_deadline_date = datetime.date.today() + datetime.timedelta(days=5)
    deadline = forms.DateField(
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"],
        required=False,
    )

    TRUE_FALSE_CHOICES = ((False, "No"), (True, "Yes"))
    is_done = forms.ChoiceField(
        choices=TRUE_FALSE_CHOICES,
        label="Is done ?",
        initial="",
        widget=forms.Select(), required=True)

    class Meta:
        model = Task
        fields = "__all__"

    def clean_deadline(self):
        return validate_deadline(self.cleaned_data["deadline"])


def validate_deadline(deadline):
    if deadline and deadline < datetime.date.today():
        raise ValidationError(
            f"Deadline date should be not less than today: "
            f"{datetime.date.today().strftime("%d-%m-%Y")}"
        )

    return deadline

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from task.forms import TaskCreationForm
from task.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")


class TaskSetDoneView(generic.DetailView):
    model = Task

    def post(self, request, **kwargs):
        self.object = self.get_object()
        self.object.is_done = not self.object.is_done
        self.object.save()
        return HttpResponseRedirect(reverse("task:task-list"))


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class TagListView(generic.ListView):
    model = Tag
    template_name = "task/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To Do List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <br>

  <li class="list-group-item"><a href="{% url 'task:task-list' %}">All Tasks</a></li>
  <li class="list-group-item"><a href="{% url 'task:tag-list' %}">All Tags</a></li>
</ul>

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag '{{ tag.name }}' ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:tag-list' %}" class="btn btn-warning">Cancel</a>
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <br>
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1> Tags List</h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'task:tag-create' %}" class="btn btn-primary link-to-page">
        + Create
      </a>
    </div>
  </div>
  
  {% if tag_list %}
    <table class="table table-hover table-striped">
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.id }}
          </td>
          <td>
            <span class="font-weight-bold">{{ tag.name }}</span>
          </td>
          <td>
              <a class="link-info" href="{% url 'task:tag-update' pk=tag.id %}">
                <span class="font-weight-bold">Update</span>
              </a>
            </td>
            <td>
              <a class="link-danger" href="{% url 'task:tag-delete' pk=tag.id %}">
                <span class="font-weight-bold">Delete</span>
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
  
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task '{{ task.content }}' ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:tag-list' %}" class="btn btn-warning">Cancel</a>
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <br>
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1> Tasks List</h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'task:task-create' %}" class="btn btn-primary link-to-page">
        + Create
      </a>
    </div>
  </div>

  {% if task_list %}
  <div class="row">
    <div class="col-md-12">
  <table class="table table-hover table-striped">

  {% for task in task_list %}
    <tr>
      <td>
        <span class="font-weight-bold h5">{{ task.content }}</span>

          {% if task.is_done %}
            <span class="font-weight-bold text-success">Done</span>
          {% else %}
            <span class="font-weight-bold text-danger">Not done</span>
          {% endif %}
      <br>
        Creation: {{ task.creation_date|date:"M d, Y, H:i"  }}
        {% if task.deadline %}
          | <span class="bg-secondary text-white"> Deadline: {{ task.deadline|date:"D, d M Y"  }}</span>
        {% endif %}
      <br>
      {% if task.tags %}
        <span class="text-muted font-weight-bold h5">
          Tags:
          {% for tag in task.tags.all %}
            {{ tag }}
          {% endfor %}
        </span>
      {% endif %}

      </span>
      </td>
      <td>
        <a class="link-info" href="{% url 'task:task-update' pk=task.id %}">
          <span class="font-weight-bold">Update</span>
        </a>
      </td>
      <td>
        <a class="link-danger" href="{% url 'task:task-delete' pk=task.id %}">
          <span class="font-weight-bold">Delete</span>
        </a>
      </td>
      <td>

          <form action="{% url 'task:task-set-done' pk=task.id %}" method="post">
            {% csrf_token %}

            {% if task.is_done %}
              <button type="submit" class="btn btn-sm btn-outline-dark link-to-page">
                <span class="font-weight-bold">Undo</span>
              </button>
            {% else %}
              <button type="submit" class="btn btn-sm btn-outline-success link-to-page">
                <span class="font-weight-bold">Complete</span>
              </button>
            {% endif %}

            </button>
          </form>

      </td>
    </tr>

  {% endfor %}

  </table>
    </div>
  </div>
  {% else %}
    <p>There are no tasks in the system.</p>
  {% endif %}

{% endblock %}